<?php
/**
 * EventCategoryDTO
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Idealogic\RegistrationAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Idealogic Event and Member Admin Service API
 *
 * Adminstrative services for managing events and members
 *
 * The version of the OpenAPI document: 2.0.6-SNAPSHOT
 * Contact: development@idealogic.co.za
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Idealogic\RegistrationAPI\Model;

use \ArrayAccess;
use \Idealogic\RegistrationAPI\ObjectSerializer;

/**
 * EventCategoryDTO Class Doc Comment
 *
 * @category Class
 * @description A catogory associated with a Series or Event. It allows setting Series and Event specific details, such as Products. Rather than having a SeriesCategory and EventCategory, this entity combines both into one. If Series is set, then it is a Series category, otherwise an Event category.
 * @package  Idealogic\RegistrationAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EventCategoryDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'EventCategoryDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'name' => 'string',
        'min_age' => 'int',
        'max_age' => 'int',
        'gender' => 'string',
        'entry_category' => 'bool',
        'race_category' => 'bool',
        'source_category' => '\Idealogic\RegistrationAPI\Model\CategoryDTO',
        'product' => '\Idealogic\RegistrationAPI\Model\ProductDTO',
        'series_category' => '\Idealogic\RegistrationAPI\Model\EventCategoryDTO',
        'feeder_categories' => '\Idealogic\RegistrationAPI\Model\EventCategoryDTO[]',
        'series' => '\Idealogic\RegistrationAPI\Model\SeriesDTO',
        'event' => '\Idealogic\RegistrationAPI\Model\EventDTO'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'int64',
        'name' => null,
        'min_age' => 'int32',
        'max_age' => 'int32',
        'gender' => null,
        'entry_category' => null,
        'race_category' => null,
        'source_category' => null,
        'product' => null,
        'series_category' => null,
        'feeder_categories' => null,
        'series' => null,
        'event' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'name' => false,
        'min_age' => false,
        'max_age' => false,
        'gender' => false,
        'entry_category' => false,
        'race_category' => false,
        'source_category' => false,
        'product' => false,
        'series_category' => false,
        'feeder_categories' => false,
        'series' => false,
        'event' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'min_age' => 'minAge',
        'max_age' => 'maxAge',
        'gender' => 'gender',
        'entry_category' => 'entryCategory',
        'race_category' => 'raceCategory',
        'source_category' => 'sourceCategory',
        'product' => 'product',
        'series_category' => 'seriesCategory',
        'feeder_categories' => 'feederCategories',
        'series' => 'series',
        'event' => 'event'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'min_age' => 'setMinAge',
        'max_age' => 'setMaxAge',
        'gender' => 'setGender',
        'entry_category' => 'setEntryCategory',
        'race_category' => 'setRaceCategory',
        'source_category' => 'setSourceCategory',
        'product' => 'setProduct',
        'series_category' => 'setSeriesCategory',
        'feeder_categories' => 'setFeederCategories',
        'series' => 'setSeries',
        'event' => 'setEvent'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'min_age' => 'getMinAge',
        'max_age' => 'getMaxAge',
        'gender' => 'getGender',
        'entry_category' => 'getEntryCategory',
        'race_category' => 'getRaceCategory',
        'source_category' => 'getSourceCategory',
        'product' => 'getProduct',
        'series_category' => 'getSeriesCategory',
        'feeder_categories' => 'getFeederCategories',
        'series' => 'getSeries',
        'event' => 'getEvent'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const GENDER_UNKNOWN = 'UNKNOWN';
    public const GENDER_MALE = 'MALE';
    public const GENDER_FEMALE = 'FEMALE';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getGenderAllowableValues()
    {
        return [
            self::GENDER_UNKNOWN,
            self::GENDER_MALE,
            self::GENDER_FEMALE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('min_age', $data ?? [], null);
        $this->setIfExists('max_age', $data ?? [], null);
        $this->setIfExists('gender', $data ?? [], null);
        $this->setIfExists('entry_category', $data ?? [], null);
        $this->setIfExists('race_category', $data ?? [], null);
        $this->setIfExists('source_category', $data ?? [], null);
        $this->setIfExists('product', $data ?? [], null);
        $this->setIfExists('series_category', $data ?? [], null);
        $this->setIfExists('feeder_categories', $data ?? [], null);
        $this->setIfExists('series', $data ?? [], null);
        $this->setIfExists('event', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 50)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 50.";
        }

        if ((mb_strlen($this->container['name']) < 0)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 0.";
        }

        $allowedValues = $this->getGenderAllowableValues();
        if (!is_null($this->container['gender']) && !in_array($this->container['gender'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'gender', must be one of '%s'",
                $this->container['gender'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        if ((mb_strlen($name) > 50)) {
            throw new \InvalidArgumentException('invalid length for $name when calling EventCategoryDTO., must be smaller than or equal to 50.');
        }
        if ((mb_strlen($name) < 0)) {
            throw new \InvalidArgumentException('invalid length for $name when calling EventCategoryDTO., must be bigger than or equal to 0.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets min_age
     *
     * @return int|null
     */
    public function getMinAge()
    {
        return $this->container['min_age'];
    }

    /**
     * Sets min_age
     *
     * @param int|null $min_age Override minimum allowed age for this category. Leave blank if not applicable.
     *
     * @return self
     */
    public function setMinAge($min_age)
    {
        if (is_null($min_age)) {
            throw new \InvalidArgumentException('non-nullable min_age cannot be null');
        }
        $this->container['min_age'] = $min_age;

        return $this;
    }

    /**
     * Gets max_age
     *
     * @return int|null
     */
    public function getMaxAge()
    {
        return $this->container['max_age'];
    }

    /**
     * Sets max_age
     *
     * @param int|null $max_age Override maximum allowed age for this category. Leave blank if not applicable.
     *
     * @return self
     */
    public function setMaxAge($max_age)
    {
        if (is_null($max_age)) {
            throw new \InvalidArgumentException('non-nullable max_age cannot be null');
        }
        $this->container['max_age'] = $max_age;

        return $this;
    }

    /**
     * Gets gender
     *
     * @return string|null
     */
    public function getGender()
    {
        return $this->container['gender'];
    }

    /**
     * Sets gender
     *
     * @param string|null $gender Override gender restriction for this category. Leave blank if not applicable.
     *
     * @return self
     */
    public function setGender($gender)
    {
        if (is_null($gender)) {
            throw new \InvalidArgumentException('non-nullable gender cannot be null');
        }
        $allowedValues = $this->getGenderAllowableValues();
        if (!in_array($gender, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'gender', must be one of '%s'",
                    $gender,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['gender'] = $gender;

        return $this;
    }

    /**
     * Gets entry_category
     *
     * @return bool|null
     */
    public function getEntryCategory()
    {
        return $this->container['entry_category'];
    }

    /**
     * Sets entry_category
     *
     * @param bool|null $entry_category Indicate if this category can be used for new entries.
     *
     * @return self
     */
    public function setEntryCategory($entry_category)
    {
        if (is_null($entry_category)) {
            throw new \InvalidArgumentException('non-nullable entry_category cannot be null');
        }
        $this->container['entry_category'] = $entry_category;

        return $this;
    }

    /**
     * Gets race_category
     *
     * @return bool|null
     */
    public function getRaceCategory()
    {
        return $this->container['race_category'];
    }

    /**
     * Sets race_category
     *
     * @param bool|null $race_category Indicate if this category can be used in races.
     *
     * @return self
     */
    public function setRaceCategory($race_category)
    {
        if (is_null($race_category)) {
            throw new \InvalidArgumentException('non-nullable race_category cannot be null');
        }
        $this->container['race_category'] = $race_category;

        return $this;
    }

    /**
     * Gets source_category
     *
     * @return \Idealogic\RegistrationAPI\Model\CategoryDTO|null
     */
    public function getSourceCategory()
    {
        return $this->container['source_category'];
    }

    /**
     * Sets source_category
     *
     * @param \Idealogic\RegistrationAPI\Model\CategoryDTO|null $source_category source_category
     *
     * @return self
     */
    public function setSourceCategory($source_category)
    {
        if (is_null($source_category)) {
            throw new \InvalidArgumentException('non-nullable source_category cannot be null');
        }
        $this->container['source_category'] = $source_category;

        return $this;
    }

    /**
     * Gets product
     *
     * @return \Idealogic\RegistrationAPI\Model\ProductDTO|null
     */
    public function getProduct()
    {
        return $this->container['product'];
    }

    /**
     * Sets product
     *
     * @param \Idealogic\RegistrationAPI\Model\ProductDTO|null $product product
     *
     * @return self
     */
    public function setProduct($product)
    {
        if (is_null($product)) {
            throw new \InvalidArgumentException('non-nullable product cannot be null');
        }
        $this->container['product'] = $product;

        return $this;
    }

    /**
     * Gets series_category
     *
     * @return \Idealogic\RegistrationAPI\Model\EventCategoryDTO|null
     */
    public function getSeriesCategory()
    {
        return $this->container['series_category'];
    }

    /**
     * Sets series_category
     *
     * @param \Idealogic\RegistrationAPI\Model\EventCategoryDTO|null $series_category series_category
     *
     * @return self
     */
    public function setSeriesCategory($series_category)
    {
        if (is_null($series_category)) {
            throw new \InvalidArgumentException('non-nullable series_category cannot be null');
        }
        $this->container['series_category'] = $series_category;

        return $this;
    }

    /**
     * Gets feeder_categories
     *
     * @return \Idealogic\RegistrationAPI\Model\EventCategoryDTO[]|null
     */
    public function getFeederCategories()
    {
        return $this->container['feeder_categories'];
    }

    /**
     * Sets feeder_categories
     *
     * @param \Idealogic\RegistrationAPI\Model\EventCategoryDTO[]|null $feeder_categories feeder_categories
     *
     * @return self
     */
    public function setFeederCategories($feeder_categories)
    {
        if (is_null($feeder_categories)) {
            throw new \InvalidArgumentException('non-nullable feeder_categories cannot be null');
        }


        $this->container['feeder_categories'] = $feeder_categories;

        return $this;
    }

    /**
     * Gets series
     *
     * @return \Idealogic\RegistrationAPI\Model\SeriesDTO|null
     */
    public function getSeries()
    {
        return $this->container['series'];
    }

    /**
     * Sets series
     *
     * @param \Idealogic\RegistrationAPI\Model\SeriesDTO|null $series series
     *
     * @return self
     */
    public function setSeries($series)
    {
        if (is_null($series)) {
            throw new \InvalidArgumentException('non-nullable series cannot be null');
        }
        $this->container['series'] = $series;

        return $this;
    }

    /**
     * Gets event
     *
     * @return \Idealogic\RegistrationAPI\Model\EventDTO|null
     */
    public function getEvent()
    {
        return $this->container['event'];
    }

    /**
     * Sets event
     *
     * @param \Idealogic\RegistrationAPI\Model\EventDTO|null $event event
     *
     * @return self
     */
    public function setEvent($event)
    {
        if (is_null($event)) {
            throw new \InvalidArgumentException('non-nullable event cannot be null');
        }
        $this->container['event'] = $event;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


