<?php
/**
 * EventCategoryDTO
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Idealogic\RegistrationAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Application API
 *
 * API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Idealogic\RegistrationAPI\Model;

use \ArrayAccess;
use \Idealogic\RegistrationAPI\ObjectSerializer;

/**
 * EventCategoryDTO Class Doc Comment
 *
 * @category Class
 * @description A category associated with a Series or Event. Combines what would otherwise be a SeriesCategory and EventCategory into one entity — a row with &#x60;series&#x60; set is a series-level category, a row with &#x60;event&#x60; set is an event-level category.  **Three-tier cascading inheritance.** Shared attributes (name, age range, gender, product, policy flags) cascade &#x60;Category → series-level EventCategory → event-level EventCategory&#x60;. Each layer can override locally.  **Origin surface.** For each inheritable field &#x60;xxx&#x60;, the DTO carries: * &#x60;xxx&#x60; — effective (cascaded) value; read + write on PUT. To clear a local override and re-inherit, send the field as null on PUT (the partial-update endpoint ignores null fields and therefore cannot clear an override). Note: &#x60;name&#x60; is currently @NotNull-validated and cannot be sent as null on either endpoint — clearing a redundant local &#x60;name&#x60; requires the data-layer cleanup, not the API. * &#x60;xxxLocal&#x60; — raw column value; read-only. &#x60;null&#x60; means \&quot;inherited, not overridden\&quot;. * &#x60;xxxOrigin&#x60; — &#x60;LOCAL&#x60; | &#x60;SERIES&#x60; | &#x60;CATEGORY&#x60; | &#x60;NONE&#x60;; read-only. Tells the UI which layer the effective value came from.  **Parentage rule.** An event-level row is in exactly one of three states: series-linked (seriesCategory set, sourceCategory null), standalone-standard (sourceCategory set, seriesCategory null), or ad-hoc (both null). Setting both pointers on an event-level row is rejected by validation.
 * @package  Idealogic\RegistrationAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EventCategoryDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'EventCategoryDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'mixed',
        'name' => 'mixed',
        'min_age' => 'mixed',
        'max_age' => 'mixed',
        'gender' => 'mixed',
        'entry_category' => 'mixed',
        'race_category' => 'mixed',
        'source_category' => 'mixed',
        'product' => '\Idealogic\RegistrationAPI\Model\ProductDTO',
        'series_category' => '\Idealogic\RegistrationAPI\Model\EventCategoryDTO',
        'feeder_categories' => 'mixed',
        'series' => '\Idealogic\RegistrationAPI\Model\SeriesDTO',
        'event' => 'mixed',
        'target_categories' => 'mixed',
        'name_local' => 'mixed',
        'name_origin' => 'mixed',
        'min_age_local' => 'mixed',
        'min_age_origin' => 'mixed',
        'max_age_local' => 'mixed',
        'max_age_origin' => 'mixed',
        'gender_local' => 'mixed',
        'gender_origin' => 'mixed',
        'entry_category_local' => 'mixed',
        'entry_category_origin' => 'mixed',
        'race_category_local' => 'mixed',
        'race_category_origin' => 'mixed',
        'source_category_local' => '\Idealogic\RegistrationAPI\Model\CategoryDTO',
        'source_category_origin' => 'mixed',
        'product_local' => '\Idealogic\RegistrationAPI\Model\ProductDTO',
        'product_origin' => 'mixed'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'int64',
        'name' => null,
        'min_age' => 'int32',
        'max_age' => 'int32',
        'gender' => null,
        'entry_category' => null,
        'race_category' => null,
        'source_category' => null,
        'product' => null,
        'series_category' => null,
        'feeder_categories' => null,
        'series' => null,
        'event' => null,
        'target_categories' => null,
        'name_local' => null,
        'name_origin' => null,
        'min_age_local' => 'int32',
        'min_age_origin' => null,
        'max_age_local' => 'int32',
        'max_age_origin' => null,
        'gender_local' => null,
        'gender_origin' => null,
        'entry_category_local' => null,
        'entry_category_origin' => null,
        'race_category_local' => null,
        'race_category_origin' => null,
        'source_category_local' => null,
        'source_category_origin' => null,
        'product_local' => null,
        'product_origin' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => true,
        'name' => true,
        'min_age' => true,
        'max_age' => true,
        'gender' => true,
        'entry_category' => true,
        'race_category' => true,
        'source_category' => true,
        'product' => false,
        'series_category' => false,
        'feeder_categories' => true,
        'series' => false,
        'event' => true,
        'target_categories' => true,
        'name_local' => true,
        'name_origin' => true,
        'min_age_local' => true,
        'min_age_origin' => true,
        'max_age_local' => true,
        'max_age_origin' => true,
        'gender_local' => true,
        'gender_origin' => true,
        'entry_category_local' => true,
        'entry_category_origin' => true,
        'race_category_local' => true,
        'race_category_origin' => true,
        'source_category_local' => false,
        'source_category_origin' => true,
        'product_local' => false,
        'product_origin' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'min_age' => 'minAge',
        'max_age' => 'maxAge',
        'gender' => 'gender',
        'entry_category' => 'entryCategory',
        'race_category' => 'raceCategory',
        'source_category' => 'sourceCategory',
        'product' => 'product',
        'series_category' => 'seriesCategory',
        'feeder_categories' => 'feederCategories',
        'series' => 'series',
        'event' => 'event',
        'target_categories' => 'targetCategories',
        'name_local' => 'nameLocal',
        'name_origin' => 'nameOrigin',
        'min_age_local' => 'minAgeLocal',
        'min_age_origin' => 'minAgeOrigin',
        'max_age_local' => 'maxAgeLocal',
        'max_age_origin' => 'maxAgeOrigin',
        'gender_local' => 'genderLocal',
        'gender_origin' => 'genderOrigin',
        'entry_category_local' => 'entryCategoryLocal',
        'entry_category_origin' => 'entryCategoryOrigin',
        'race_category_local' => 'raceCategoryLocal',
        'race_category_origin' => 'raceCategoryOrigin',
        'source_category_local' => 'sourceCategoryLocal',
        'source_category_origin' => 'sourceCategoryOrigin',
        'product_local' => 'productLocal',
        'product_origin' => 'productOrigin'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'min_age' => 'setMinAge',
        'max_age' => 'setMaxAge',
        'gender' => 'setGender',
        'entry_category' => 'setEntryCategory',
        'race_category' => 'setRaceCategory',
        'source_category' => 'setSourceCategory',
        'product' => 'setProduct',
        'series_category' => 'setSeriesCategory',
        'feeder_categories' => 'setFeederCategories',
        'series' => 'setSeries',
        'event' => 'setEvent',
        'target_categories' => 'setTargetCategories',
        'name_local' => 'setNameLocal',
        'name_origin' => 'setNameOrigin',
        'min_age_local' => 'setMinAgeLocal',
        'min_age_origin' => 'setMinAgeOrigin',
        'max_age_local' => 'setMaxAgeLocal',
        'max_age_origin' => 'setMaxAgeOrigin',
        'gender_local' => 'setGenderLocal',
        'gender_origin' => 'setGenderOrigin',
        'entry_category_local' => 'setEntryCategoryLocal',
        'entry_category_origin' => 'setEntryCategoryOrigin',
        'race_category_local' => 'setRaceCategoryLocal',
        'race_category_origin' => 'setRaceCategoryOrigin',
        'source_category_local' => 'setSourceCategoryLocal',
        'source_category_origin' => 'setSourceCategoryOrigin',
        'product_local' => 'setProductLocal',
        'product_origin' => 'setProductOrigin'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'min_age' => 'getMinAge',
        'max_age' => 'getMaxAge',
        'gender' => 'getGender',
        'entry_category' => 'getEntryCategory',
        'race_category' => 'getRaceCategory',
        'source_category' => 'getSourceCategory',
        'product' => 'getProduct',
        'series_category' => 'getSeriesCategory',
        'feeder_categories' => 'getFeederCategories',
        'series' => 'getSeries',
        'event' => 'getEvent',
        'target_categories' => 'getTargetCategories',
        'name_local' => 'getNameLocal',
        'name_origin' => 'getNameOrigin',
        'min_age_local' => 'getMinAgeLocal',
        'min_age_origin' => 'getMinAgeOrigin',
        'max_age_local' => 'getMaxAgeLocal',
        'max_age_origin' => 'getMaxAgeOrigin',
        'gender_local' => 'getGenderLocal',
        'gender_origin' => 'getGenderOrigin',
        'entry_category_local' => 'getEntryCategoryLocal',
        'entry_category_origin' => 'getEntryCategoryOrigin',
        'race_category_local' => 'getRaceCategoryLocal',
        'race_category_origin' => 'getRaceCategoryOrigin',
        'source_category_local' => 'getSourceCategoryLocal',
        'source_category_origin' => 'getSourceCategoryOrigin',
        'product_local' => 'getProductLocal',
        'product_origin' => 'getProductOrigin'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const GENDER_UNKNOWN = 'UNKNOWN';
    public const GENDER_MALE = 'MALE';
    public const GENDER_FEMALE = 'FEMALE';
    public const NAME_ORIGIN_LOCAL = 'LOCAL';
    public const NAME_ORIGIN_SERIES = 'SERIES';
    public const NAME_ORIGIN_CATEGORY = 'CATEGORY';
    public const NAME_ORIGIN_NONE = 'NONE';
    public const MIN_AGE_ORIGIN_LOCAL = 'LOCAL';
    public const MIN_AGE_ORIGIN_SERIES = 'SERIES';
    public const MIN_AGE_ORIGIN_CATEGORY = 'CATEGORY';
    public const MIN_AGE_ORIGIN_NONE = 'NONE';
    public const MAX_AGE_ORIGIN_LOCAL = 'LOCAL';
    public const MAX_AGE_ORIGIN_SERIES = 'SERIES';
    public const MAX_AGE_ORIGIN_CATEGORY = 'CATEGORY';
    public const MAX_AGE_ORIGIN_NONE = 'NONE';
    public const GENDER_LOCAL_UNKNOWN = 'UNKNOWN';
    public const GENDER_LOCAL_MALE = 'MALE';
    public const GENDER_LOCAL_FEMALE = 'FEMALE';
    public const GENDER_ORIGIN_LOCAL = 'LOCAL';
    public const GENDER_ORIGIN_SERIES = 'SERIES';
    public const GENDER_ORIGIN_CATEGORY = 'CATEGORY';
    public const GENDER_ORIGIN_NONE = 'NONE';
    public const ENTRY_CATEGORY_ORIGIN_LOCAL = 'LOCAL';
    public const ENTRY_CATEGORY_ORIGIN_SERIES = 'SERIES';
    public const ENTRY_CATEGORY_ORIGIN_CATEGORY = 'CATEGORY';
    public const ENTRY_CATEGORY_ORIGIN_NONE = 'NONE';
    public const RACE_CATEGORY_ORIGIN_LOCAL = 'LOCAL';
    public const RACE_CATEGORY_ORIGIN_SERIES = 'SERIES';
    public const RACE_CATEGORY_ORIGIN_CATEGORY = 'CATEGORY';
    public const RACE_CATEGORY_ORIGIN_NONE = 'NONE';
    public const SOURCE_CATEGORY_ORIGIN_LOCAL = 'LOCAL';
    public const SOURCE_CATEGORY_ORIGIN_SERIES = 'SERIES';
    public const SOURCE_CATEGORY_ORIGIN_CATEGORY = 'CATEGORY';
    public const SOURCE_CATEGORY_ORIGIN_NONE = 'NONE';
    public const PRODUCT_ORIGIN_LOCAL = 'LOCAL';
    public const PRODUCT_ORIGIN_SERIES = 'SERIES';
    public const PRODUCT_ORIGIN_CATEGORY = 'CATEGORY';
    public const PRODUCT_ORIGIN_NONE = 'NONE';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getGenderAllowableValues()
    {
        return [
            self::GENDER_UNKNOWN,
            self::GENDER_MALE,
            self::GENDER_FEMALE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getNameOriginAllowableValues()
    {
        return [
            self::NAME_ORIGIN_LOCAL,
            self::NAME_ORIGIN_SERIES,
            self::NAME_ORIGIN_CATEGORY,
            self::NAME_ORIGIN_NONE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getMinAgeOriginAllowableValues()
    {
        return [
            self::MIN_AGE_ORIGIN_LOCAL,
            self::MIN_AGE_ORIGIN_SERIES,
            self::MIN_AGE_ORIGIN_CATEGORY,
            self::MIN_AGE_ORIGIN_NONE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getMaxAgeOriginAllowableValues()
    {
        return [
            self::MAX_AGE_ORIGIN_LOCAL,
            self::MAX_AGE_ORIGIN_SERIES,
            self::MAX_AGE_ORIGIN_CATEGORY,
            self::MAX_AGE_ORIGIN_NONE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getGenderLocalAllowableValues()
    {
        return [
            self::GENDER_LOCAL_UNKNOWN,
            self::GENDER_LOCAL_MALE,
            self::GENDER_LOCAL_FEMALE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getGenderOriginAllowableValues()
    {
        return [
            self::GENDER_ORIGIN_LOCAL,
            self::GENDER_ORIGIN_SERIES,
            self::GENDER_ORIGIN_CATEGORY,
            self::GENDER_ORIGIN_NONE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEntryCategoryOriginAllowableValues()
    {
        return [
            self::ENTRY_CATEGORY_ORIGIN_LOCAL,
            self::ENTRY_CATEGORY_ORIGIN_SERIES,
            self::ENTRY_CATEGORY_ORIGIN_CATEGORY,
            self::ENTRY_CATEGORY_ORIGIN_NONE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRaceCategoryOriginAllowableValues()
    {
        return [
            self::RACE_CATEGORY_ORIGIN_LOCAL,
            self::RACE_CATEGORY_ORIGIN_SERIES,
            self::RACE_CATEGORY_ORIGIN_CATEGORY,
            self::RACE_CATEGORY_ORIGIN_NONE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSourceCategoryOriginAllowableValues()
    {
        return [
            self::SOURCE_CATEGORY_ORIGIN_LOCAL,
            self::SOURCE_CATEGORY_ORIGIN_SERIES,
            self::SOURCE_CATEGORY_ORIGIN_CATEGORY,
            self::SOURCE_CATEGORY_ORIGIN_NONE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getProductOriginAllowableValues()
    {
        return [
            self::PRODUCT_ORIGIN_LOCAL,
            self::PRODUCT_ORIGIN_SERIES,
            self::PRODUCT_ORIGIN_CATEGORY,
            self::PRODUCT_ORIGIN_NONE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('min_age', $data ?? [], null);
        $this->setIfExists('max_age', $data ?? [], null);
        $this->setIfExists('gender', $data ?? [], null);
        $this->setIfExists('entry_category', $data ?? [], null);
        $this->setIfExists('race_category', $data ?? [], null);
        $this->setIfExists('source_category', $data ?? [], null);
        $this->setIfExists('product', $data ?? [], null);
        $this->setIfExists('series_category', $data ?? [], null);
        $this->setIfExists('feeder_categories', $data ?? [], null);
        $this->setIfExists('series', $data ?? [], null);
        $this->setIfExists('event', $data ?? [], null);
        $this->setIfExists('target_categories', $data ?? [], null);
        $this->setIfExists('name_local', $data ?? [], null);
        $this->setIfExists('name_origin', $data ?? [], null);
        $this->setIfExists('min_age_local', $data ?? [], null);
        $this->setIfExists('min_age_origin', $data ?? [], null);
        $this->setIfExists('max_age_local', $data ?? [], null);
        $this->setIfExists('max_age_origin', $data ?? [], null);
        $this->setIfExists('gender_local', $data ?? [], null);
        $this->setIfExists('gender_origin', $data ?? [], null);
        $this->setIfExists('entry_category_local', $data ?? [], null);
        $this->setIfExists('entry_category_origin', $data ?? [], null);
        $this->setIfExists('race_category_local', $data ?? [], null);
        $this->setIfExists('race_category_origin', $data ?? [], null);
        $this->setIfExists('source_category_local', $data ?? [], null);
        $this->setIfExists('source_category_origin', $data ?? [], null);
        $this->setIfExists('product_local', $data ?? [], null);
        $this->setIfExists('product_origin', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 50)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 50.";
        }

        if ((mb_strlen($this->container['name']) < 0)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 0.";
        }

        $allowedValues = $this->getGenderAllowableValues();
        if (!is_null($this->container['gender']) && !in_array($this->container['gender'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'gender', must be one of '%s'",
                $this->container['gender'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getNameOriginAllowableValues();
        if (!is_null($this->container['name_origin']) && !in_array($this->container['name_origin'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'name_origin', must be one of '%s'",
                $this->container['name_origin'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getMinAgeOriginAllowableValues();
        if (!is_null($this->container['min_age_origin']) && !in_array($this->container['min_age_origin'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'min_age_origin', must be one of '%s'",
                $this->container['min_age_origin'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getMaxAgeOriginAllowableValues();
        if (!is_null($this->container['max_age_origin']) && !in_array($this->container['max_age_origin'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'max_age_origin', must be one of '%s'",
                $this->container['max_age_origin'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getGenderLocalAllowableValues();
        if (!is_null($this->container['gender_local']) && !in_array($this->container['gender_local'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'gender_local', must be one of '%s'",
                $this->container['gender_local'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getGenderOriginAllowableValues();
        if (!is_null($this->container['gender_origin']) && !in_array($this->container['gender_origin'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'gender_origin', must be one of '%s'",
                $this->container['gender_origin'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getEntryCategoryOriginAllowableValues();
        if (!is_null($this->container['entry_category_origin']) && !in_array($this->container['entry_category_origin'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'entry_category_origin', must be one of '%s'",
                $this->container['entry_category_origin'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getRaceCategoryOriginAllowableValues();
        if (!is_null($this->container['race_category_origin']) && !in_array($this->container['race_category_origin'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'race_category_origin', must be one of '%s'",
                $this->container['race_category_origin'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getSourceCategoryOriginAllowableValues();
        if (!is_null($this->container['source_category_origin']) && !in_array($this->container['source_category_origin'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'source_category_origin', must be one of '%s'",
                $this->container['source_category_origin'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getProductOriginAllowableValues();
        if (!is_null($this->container['product_origin']) && !in_array($this->container['product_origin'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'product_origin', must be one of '%s'",
                $this->container['product_origin'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return mixed|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param mixed|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            array_push($this->openAPINullablesSetToNull, 'id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return mixed
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param mixed $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            array_push($this->openAPINullablesSetToNull, 'name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($name) && (mb_strlen($name) > 50)) {
            throw new \InvalidArgumentException('invalid length for $name when calling EventCategoryDTO., must be smaller than or equal to 50.');
        }
        if (!is_null($name) && (mb_strlen($name) < 0)) {
            throw new \InvalidArgumentException('invalid length for $name when calling EventCategoryDTO., must be bigger than or equal to 0.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets min_age
     *
     * @return mixed|null
     */
    public function getMinAge()
    {
        return $this->container['min_age'];
    }

    /**
     * Sets min_age
     *
     * @param mixed|null $min_age Effective minimum allowed age — cascaded from seriesCategory or sourceCategory if not set locally. Set null on write to clear the local override and re-inherit.
     *
     * @return self
     */
    public function setMinAge($min_age)
    {
        if (is_null($min_age)) {
            array_push($this->openAPINullablesSetToNull, 'min_age');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('min_age', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['min_age'] = $min_age;

        return $this;
    }

    /**
     * Gets max_age
     *
     * @return mixed|null
     */
    public function getMaxAge()
    {
        return $this->container['max_age'];
    }

    /**
     * Sets max_age
     *
     * @param mixed|null $max_age Effective maximum allowed age — cascaded from seriesCategory or sourceCategory if not set locally. Set null on write to clear the local override and re-inherit.
     *
     * @return self
     */
    public function setMaxAge($max_age)
    {
        if (is_null($max_age)) {
            array_push($this->openAPINullablesSetToNull, 'max_age');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('max_age', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['max_age'] = $max_age;

        return $this;
    }

    /**
     * Gets gender
     *
     * @return mixed|null
     */
    public function getGender()
    {
        return $this->container['gender'];
    }

    /**
     * Sets gender
     *
     * @param mixed|null $gender Effective gender restriction — cascaded from seriesCategory or sourceCategory if not set locally. Set null on write to clear the local override and re-inherit.
     *
     * @return self
     */
    public function setGender($gender)
    {
        if (is_null($gender)) {
            array_push($this->openAPINullablesSetToNull, 'gender');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('gender', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getGenderAllowableValues();
        if (!is_null($gender) && !in_array($gender, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'gender', must be one of '%s'",
                    $gender,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['gender'] = $gender;

        return $this;
    }

    /**
     * Gets entry_category
     *
     * @return mixed|null
     */
    public function getEntryCategory()
    {
        return $this->container['entry_category'];
    }

    /**
     * Sets entry_category
     *
     * @param mixed|null $entry_category Effective entry-allowed flag — cascaded from seriesCategory if not set locally. Null means no inherited policy.
     *
     * @return self
     */
    public function setEntryCategory($entry_category)
    {
        if (is_null($entry_category)) {
            array_push($this->openAPINullablesSetToNull, 'entry_category');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('entry_category', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['entry_category'] = $entry_category;

        return $this;
    }

    /**
     * Gets race_category
     *
     * @return mixed|null
     */
    public function getRaceCategory()
    {
        return $this->container['race_category'];
    }

    /**
     * Sets race_category
     *
     * @param mixed|null $race_category Effective race-allowed flag — cascaded from seriesCategory if not set locally. Null means no inherited policy.
     *
     * @return self
     */
    public function setRaceCategory($race_category)
    {
        if (is_null($race_category)) {
            array_push($this->openAPINullablesSetToNull, 'race_category');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('race_category', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['race_category'] = $race_category;

        return $this;
    }

    /**
     * Gets source_category
     *
     * @return mixed|null
     */
    public function getSourceCategory()
    {
        return $this->container['source_category'];
    }

    /**
     * Sets source_category
     *
     * @param mixed|null $source_category Effective sourceCategory — the organisational Category template. On an event-level row this cascades from seriesCategory.sourceCategory if not set locally. The parentage rule forbids setting both sourceCategory and seriesCategory on the same event-level row.
     *
     * @return self
     */
    public function setSourceCategory($source_category)
    {
        if (is_null($source_category)) {
            array_push($this->openAPINullablesSetToNull, 'source_category');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('source_category', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['source_category'] = $source_category;

        return $this;
    }

    /**
     * Gets product
     *
     * @return \Idealogic\RegistrationAPI\Model\ProductDTO|null
     */
    public function getProduct()
    {
        return $this->container['product'];
    }

    /**
     * Sets product
     *
     * @param \Idealogic\RegistrationAPI\Model\ProductDTO|null $product Effective product — cascaded from seriesCategory if not set locally. Used when creating an entry based on this category.
     *
     * @return self
     */
    public function setProduct($product)
    {
        if (is_null($product)) {
            throw new \InvalidArgumentException('non-nullable product cannot be null');
        }
        $this->container['product'] = $product;

        return $this;
    }

    /**
     * Gets series_category
     *
     * @return \Idealogic\RegistrationAPI\Model\EventCategoryDTO|null
     */
    public function getSeriesCategory()
    {
        return $this->container['series_category'];
    }

    /**
     * Sets series_category
     *
     * @param \Idealogic\RegistrationAPI\Model\EventCategoryDTO|null $series_category If this is an Event category, this is the underlying Series category it is based on.
     *
     * @return self
     */
    public function setSeriesCategory($series_category)
    {
        if (is_null($series_category)) {
            throw new \InvalidArgumentException('non-nullable series_category cannot be null');
        }
        $this->container['series_category'] = $series_category;

        return $this;
    }

    /**
     * Gets feeder_categories
     *
     * @return mixed|null
     */
    public function getFeederCategories()
    {
        return $this->container['feeder_categories'];
    }

    /**
     * Sets feeder_categories
     *
     * @param mixed|null $feeder_categories Event Categories that feed into this event. Only applicable for race categories (raceCategory = true) and where sourceCategories are not set (thus ad-hoc EventCategories).
     *
     * @return self
     */
    public function setFeederCategories($feeder_categories)
    {
        if (is_null($feeder_categories)) {
            array_push($this->openAPINullablesSetToNull, 'feeder_categories');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('feeder_categories', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }


        $this->container['feeder_categories'] = $feeder_categories;

        return $this;
    }

    /**
     * Gets series
     *
     * @return \Idealogic\RegistrationAPI\Model\SeriesDTO|null
     */
    public function getSeries()
    {
        return $this->container['series'];
    }

    /**
     * Sets series
     *
     * @param \Idealogic\RegistrationAPI\Model\SeriesDTO|null $series series
     *
     * @return self
     */
    public function setSeries($series)
    {
        if (is_null($series)) {
            throw new \InvalidArgumentException('non-nullable series cannot be null');
        }
        $this->container['series'] = $series;

        return $this;
    }

    /**
     * Gets event
     *
     * @return mixed|null
     */
    public function getEvent()
    {
        return $this->container['event'];
    }

    /**
     * Sets event
     *
     * @param mixed|null $event An event is a collection of one or more races (activities) are held on a day or series of days.
     *
     * @return self
     */
    public function setEvent($event)
    {
        if (is_null($event)) {
            array_push($this->openAPINullablesSetToNull, 'event');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('event', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['event'] = $event;

        return $this;
    }

    /**
     * Gets target_categories
     *
     * @return mixed|null
     */
    public function getTargetCategories()
    {
        return $this->container['target_categories'];
    }

    /**
     * Sets target_categories
     *
     * @param mixed|null $target_categories target_categories
     *
     * @return self
     */
    public function setTargetCategories($target_categories)
    {
        if (is_null($target_categories)) {
            array_push($this->openAPINullablesSetToNull, 'target_categories');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('target_categories', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }


        $this->container['target_categories'] = $target_categories;

        return $this;
    }

    /**
     * Gets name_local
     *
     * @return mixed|null
     */
    public function getNameLocal()
    {
        return $this->container['name_local'];
    }

    /**
     * Sets name_local
     *
     * @param mixed|null $name_local Raw name column (null = inherited from seriesCategory or sourceCategory).
     *
     * @return self
     */
    public function setNameLocal($name_local)
    {
        if (is_null($name_local)) {
            array_push($this->openAPINullablesSetToNull, 'name_local');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name_local', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['name_local'] = $name_local;

        return $this;
    }

    /**
     * Gets name_origin
     *
     * @return mixed|null
     */
    public function getNameOrigin()
    {
        return $this->container['name_origin'];
    }

    /**
     * Sets name_origin
     *
     * @param mixed|null $name_origin Where the effective name value came from.
     *
     * @return self
     */
    public function setNameOrigin($name_origin)
    {
        if (is_null($name_origin)) {
            array_push($this->openAPINullablesSetToNull, 'name_origin');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name_origin', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getNameOriginAllowableValues();
        if (!is_null($name_origin) && !in_array($name_origin, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'name_origin', must be one of '%s'",
                    $name_origin,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['name_origin'] = $name_origin;

        return $this;
    }

    /**
     * Gets min_age_local
     *
     * @return mixed|null
     */
    public function getMinAgeLocal()
    {
        return $this->container['min_age_local'];
    }

    /**
     * Sets min_age_local
     *
     * @param mixed|null $min_age_local Raw minAge column (null = inherited).
     *
     * @return self
     */
    public function setMinAgeLocal($min_age_local)
    {
        if (is_null($min_age_local)) {
            array_push($this->openAPINullablesSetToNull, 'min_age_local');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('min_age_local', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['min_age_local'] = $min_age_local;

        return $this;
    }

    /**
     * Gets min_age_origin
     *
     * @return mixed|null
     */
    public function getMinAgeOrigin()
    {
        return $this->container['min_age_origin'];
    }

    /**
     * Sets min_age_origin
     *
     * @param mixed|null $min_age_origin Where the effective minAge value came from.
     *
     * @return self
     */
    public function setMinAgeOrigin($min_age_origin)
    {
        if (is_null($min_age_origin)) {
            array_push($this->openAPINullablesSetToNull, 'min_age_origin');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('min_age_origin', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getMinAgeOriginAllowableValues();
        if (!is_null($min_age_origin) && !in_array($min_age_origin, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'min_age_origin', must be one of '%s'",
                    $min_age_origin,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['min_age_origin'] = $min_age_origin;

        return $this;
    }

    /**
     * Gets max_age_local
     *
     * @return mixed|null
     */
    public function getMaxAgeLocal()
    {
        return $this->container['max_age_local'];
    }

    /**
     * Sets max_age_local
     *
     * @param mixed|null $max_age_local Raw maxAge column (null = inherited).
     *
     * @return self
     */
    public function setMaxAgeLocal($max_age_local)
    {
        if (is_null($max_age_local)) {
            array_push($this->openAPINullablesSetToNull, 'max_age_local');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('max_age_local', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['max_age_local'] = $max_age_local;

        return $this;
    }

    /**
     * Gets max_age_origin
     *
     * @return mixed|null
     */
    public function getMaxAgeOrigin()
    {
        return $this->container['max_age_origin'];
    }

    /**
     * Sets max_age_origin
     *
     * @param mixed|null $max_age_origin Where the effective maxAge value came from.
     *
     * @return self
     */
    public function setMaxAgeOrigin($max_age_origin)
    {
        if (is_null($max_age_origin)) {
            array_push($this->openAPINullablesSetToNull, 'max_age_origin');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('max_age_origin', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getMaxAgeOriginAllowableValues();
        if (!is_null($max_age_origin) && !in_array($max_age_origin, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'max_age_origin', must be one of '%s'",
                    $max_age_origin,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['max_age_origin'] = $max_age_origin;

        return $this;
    }

    /**
     * Gets gender_local
     *
     * @return mixed|null
     */
    public function getGenderLocal()
    {
        return $this->container['gender_local'];
    }

    /**
     * Sets gender_local
     *
     * @param mixed|null $gender_local Raw gender column (null = inherited; distinct from UNKNOWN which is a legitimate value).
     *
     * @return self
     */
    public function setGenderLocal($gender_local)
    {
        if (is_null($gender_local)) {
            array_push($this->openAPINullablesSetToNull, 'gender_local');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('gender_local', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getGenderLocalAllowableValues();
        if (!is_null($gender_local) && !in_array($gender_local, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'gender_local', must be one of '%s'",
                    $gender_local,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['gender_local'] = $gender_local;

        return $this;
    }

    /**
     * Gets gender_origin
     *
     * @return mixed|null
     */
    public function getGenderOrigin()
    {
        return $this->container['gender_origin'];
    }

    /**
     * Sets gender_origin
     *
     * @param mixed|null $gender_origin Where the effective gender value came from.
     *
     * @return self
     */
    public function setGenderOrigin($gender_origin)
    {
        if (is_null($gender_origin)) {
            array_push($this->openAPINullablesSetToNull, 'gender_origin');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('gender_origin', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getGenderOriginAllowableValues();
        if (!is_null($gender_origin) && !in_array($gender_origin, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'gender_origin', must be one of '%s'",
                    $gender_origin,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['gender_origin'] = $gender_origin;

        return $this;
    }

    /**
     * Gets entry_category_local
     *
     * @return mixed|null
     */
    public function getEntryCategoryLocal()
    {
        return $this->container['entry_category_local'];
    }

    /**
     * Sets entry_category_local
     *
     * @param mixed|null $entry_category_local Raw entryCategory column (null = no inherited policy).
     *
     * @return self
     */
    public function setEntryCategoryLocal($entry_category_local)
    {
        if (is_null($entry_category_local)) {
            array_push($this->openAPINullablesSetToNull, 'entry_category_local');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('entry_category_local', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['entry_category_local'] = $entry_category_local;

        return $this;
    }

    /**
     * Gets entry_category_origin
     *
     * @return mixed|null
     */
    public function getEntryCategoryOrigin()
    {
        return $this->container['entry_category_origin'];
    }

    /**
     * Sets entry_category_origin
     *
     * @param mixed|null $entry_category_origin Where the effective entryCategory policy came from.
     *
     * @return self
     */
    public function setEntryCategoryOrigin($entry_category_origin)
    {
        if (is_null($entry_category_origin)) {
            array_push($this->openAPINullablesSetToNull, 'entry_category_origin');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('entry_category_origin', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getEntryCategoryOriginAllowableValues();
        if (!is_null($entry_category_origin) && !in_array($entry_category_origin, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'entry_category_origin', must be one of '%s'",
                    $entry_category_origin,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['entry_category_origin'] = $entry_category_origin;

        return $this;
    }

    /**
     * Gets race_category_local
     *
     * @return mixed|null
     */
    public function getRaceCategoryLocal()
    {
        return $this->container['race_category_local'];
    }

    /**
     * Sets race_category_local
     *
     * @param mixed|null $race_category_local Raw raceCategory column (null = no inherited policy).
     *
     * @return self
     */
    public function setRaceCategoryLocal($race_category_local)
    {
        if (is_null($race_category_local)) {
            array_push($this->openAPINullablesSetToNull, 'race_category_local');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('race_category_local', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['race_category_local'] = $race_category_local;

        return $this;
    }

    /**
     * Gets race_category_origin
     *
     * @return mixed|null
     */
    public function getRaceCategoryOrigin()
    {
        return $this->container['race_category_origin'];
    }

    /**
     * Sets race_category_origin
     *
     * @param mixed|null $race_category_origin Where the effective raceCategory policy came from.
     *
     * @return self
     */
    public function setRaceCategoryOrigin($race_category_origin)
    {
        if (is_null($race_category_origin)) {
            array_push($this->openAPINullablesSetToNull, 'race_category_origin');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('race_category_origin', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getRaceCategoryOriginAllowableValues();
        if (!is_null($race_category_origin) && !in_array($race_category_origin, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'race_category_origin', must be one of '%s'",
                    $race_category_origin,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['race_category_origin'] = $race_category_origin;

        return $this;
    }

    /**
     * Gets source_category_local
     *
     * @return \Idealogic\RegistrationAPI\Model\CategoryDTO|null
     */
    public function getSourceCategoryLocal()
    {
        return $this->container['source_category_local'];
    }

    /**
     * Sets source_category_local
     *
     * @param \Idealogic\RegistrationAPI\Model\CategoryDTO|null $source_category_local Raw sourceCategory FK (null = inherited from seriesCategory; never both set on an event-level row).
     *
     * @return self
     */
    public function setSourceCategoryLocal($source_category_local)
    {
        if (is_null($source_category_local)) {
            throw new \InvalidArgumentException('non-nullable source_category_local cannot be null');
        }
        $this->container['source_category_local'] = $source_category_local;

        return $this;
    }

    /**
     * Gets source_category_origin
     *
     * @return mixed|null
     */
    public function getSourceCategoryOrigin()
    {
        return $this->container['source_category_origin'];
    }

    /**
     * Sets source_category_origin
     *
     * @param mixed|null $source_category_origin Where the effective sourceCategory came from.
     *
     * @return self
     */
    public function setSourceCategoryOrigin($source_category_origin)
    {
        if (is_null($source_category_origin)) {
            array_push($this->openAPINullablesSetToNull, 'source_category_origin');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('source_category_origin', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getSourceCategoryOriginAllowableValues();
        if (!is_null($source_category_origin) && !in_array($source_category_origin, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'source_category_origin', must be one of '%s'",
                    $source_category_origin,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['source_category_origin'] = $source_category_origin;

        return $this;
    }

    /**
     * Gets product_local
     *
     * @return \Idealogic\RegistrationAPI\Model\ProductDTO|null
     */
    public function getProductLocal()
    {
        return $this->container['product_local'];
    }

    /**
     * Sets product_local
     *
     * @param \Idealogic\RegistrationAPI\Model\ProductDTO|null $product_local Raw product FK (null = inherited from seriesCategory).
     *
     * @return self
     */
    public function setProductLocal($product_local)
    {
        if (is_null($product_local)) {
            throw new \InvalidArgumentException('non-nullable product_local cannot be null');
        }
        $this->container['product_local'] = $product_local;

        return $this;
    }

    /**
     * Gets product_origin
     *
     * @return mixed|null
     */
    public function getProductOrigin()
    {
        return $this->container['product_origin'];
    }

    /**
     * Sets product_origin
     *
     * @param mixed|null $product_origin Where the effective product came from.
     *
     * @return self
     */
    public function setProductOrigin($product_origin)
    {
        if (is_null($product_origin)) {
            array_push($this->openAPINullablesSetToNull, 'product_origin');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('product_origin', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getProductOriginAllowableValues();
        if (!is_null($product_origin) && !in_array($product_origin, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'product_origin', must be one of '%s'",
                    $product_origin,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['product_origin'] = $product_origin;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


