<?php
/**
 * RecordDTO
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Idealogic\RegistrationAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Idealogic Event and Member Admin Service API
 *
 * Administrative services for managing events and members
 *
 * The version of the OpenAPI document: 2.4.15-SNAPSHOT
 * Contact: development@idealogic.co.za
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Idealogic\RegistrationAPI\Model;

use \ArrayAccess;
use \Idealogic\RegistrationAPI\ObjectSerializer;

/**
 * RecordDTO Class Doc Comment
 *
 * @category Class
 * @package  Idealogic\RegistrationAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RecordDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RecordDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'mixed',
        'date' => 'mixed',
        'names' => 'mixed',
        'location' => 'mixed',
        'distance' => 'mixed',
        'time' => 'mixed',
        'race_type' => '\Idealogic\RegistrationAPI\Model\RaceTypeDTO',
        'category' => '\Idealogic\RegistrationAPI\Model\CategoryDTO'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'int64',
        'date' => 'date',
        'names' => null,
        'location' => null,
        'distance' => null,
        'time' => null,
        'race_type' => null,
        'category' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => true,
        'date' => true,
        'names' => true,
        'location' => true,
        'distance' => true,
        'time' => true,
        'race_type' => false,
        'category' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'date' => 'date',
        'names' => 'names',
        'location' => 'location',
        'distance' => 'distance',
        'time' => 'time',
        'race_type' => 'raceType',
        'category' => 'category'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'date' => 'setDate',
        'names' => 'setNames',
        'location' => 'setLocation',
        'distance' => 'setDistance',
        'time' => 'setTime',
        'race_type' => 'setRaceType',
        'category' => 'setCategory'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'date' => 'getDate',
        'names' => 'getNames',
        'location' => 'getLocation',
        'distance' => 'getDistance',
        'time' => 'getTime',
        'race_type' => 'getRaceType',
        'category' => 'getCategory'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('date', $data ?? [], null);
        $this->setIfExists('names', $data ?? [], null);
        $this->setIfExists('location', $data ?? [], null);
        $this->setIfExists('distance', $data ?? [], null);
        $this->setIfExists('time', $data ?? [], null);
        $this->setIfExists('race_type', $data ?? [], null);
        $this->setIfExists('category', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['names']) && (mb_strlen($this->container['names']) > 200)) {
            $invalidProperties[] = "invalid value for 'names', the character length must be smaller than or equal to 200.";
        }

        if (!is_null($this->container['names']) && (mb_strlen($this->container['names']) < 0)) {
            $invalidProperties[] = "invalid value for 'names', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['location']) && (mb_strlen($this->container['location']) > 50)) {
            $invalidProperties[] = "invalid value for 'location', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['location']) && (mb_strlen($this->container['location']) < 0)) {
            $invalidProperties[] = "invalid value for 'location', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['distance']) && (mb_strlen($this->container['distance']) > 10)) {
            $invalidProperties[] = "invalid value for 'distance', the character length must be smaller than or equal to 10.";
        }

        if (!is_null($this->container['distance']) && (mb_strlen($this->container['distance']) < 0)) {
            $invalidProperties[] = "invalid value for 'distance', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['time']) && (mb_strlen($this->container['time']) > 8)) {
            $invalidProperties[] = "invalid value for 'time', the character length must be smaller than or equal to 8.";
        }

        if (!is_null($this->container['time']) && (mb_strlen($this->container['time']) < 0)) {
            $invalidProperties[] = "invalid value for 'time', the character length must be bigger than or equal to 0.";
        }

        if ($this->container['race_type'] === null) {
            $invalidProperties[] = "'race_type' can't be null";
        }
        if ($this->container['category'] === null) {
            $invalidProperties[] = "'category' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return mixed|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param mixed|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            array_push($this->openAPINullablesSetToNull, 'id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets date
     *
     * @return mixed|null
     */
    public function getDate()
    {
        return $this->container['date'];
    }

    /**
     * Sets date
     *
     * @param mixed|null $date date
     *
     * @return self
     */
    public function setDate($date)
    {
        if (is_null($date)) {
            array_push($this->openAPINullablesSetToNull, 'date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date'] = $date;

        return $this;
    }

    /**
     * Gets names
     *
     * @return mixed|null
     */
    public function getNames()
    {
        return $this->container['names'];
    }

    /**
     * Sets names
     *
     * @param mixed|null $names names
     *
     * @return self
     */
    public function setNames($names)
    {
        if (is_null($names)) {
            array_push($this->openAPINullablesSetToNull, 'names');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('names', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($names) && (mb_strlen($names) > 200)) {
            throw new \InvalidArgumentException('invalid length for $names when calling RecordDTO., must be smaller than or equal to 200.');
        }
        if (!is_null($names) && (mb_strlen($names) < 0)) {
            throw new \InvalidArgumentException('invalid length for $names when calling RecordDTO., must be bigger than or equal to 0.');
        }

        $this->container['names'] = $names;

        return $this;
    }

    /**
     * Gets location
     *
     * @return mixed|null
     */
    public function getLocation()
    {
        return $this->container['location'];
    }

    /**
     * Sets location
     *
     * @param mixed|null $location location
     *
     * @return self
     */
    public function setLocation($location)
    {
        if (is_null($location)) {
            array_push($this->openAPINullablesSetToNull, 'location');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('location', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($location) && (mb_strlen($location) > 50)) {
            throw new \InvalidArgumentException('invalid length for $location when calling RecordDTO., must be smaller than or equal to 50.');
        }
        if (!is_null($location) && (mb_strlen($location) < 0)) {
            throw new \InvalidArgumentException('invalid length for $location when calling RecordDTO., must be bigger than or equal to 0.');
        }

        $this->container['location'] = $location;

        return $this;
    }

    /**
     * Gets distance
     *
     * @return mixed|null
     */
    public function getDistance()
    {
        return $this->container['distance'];
    }

    /**
     * Sets distance
     *
     * @param mixed|null $distance distance
     *
     * @return self
     */
    public function setDistance($distance)
    {
        if (is_null($distance)) {
            array_push($this->openAPINullablesSetToNull, 'distance');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('distance', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($distance) && (mb_strlen($distance) > 10)) {
            throw new \InvalidArgumentException('invalid length for $distance when calling RecordDTO., must be smaller than or equal to 10.');
        }
        if (!is_null($distance) && (mb_strlen($distance) < 0)) {
            throw new \InvalidArgumentException('invalid length for $distance when calling RecordDTO., must be bigger than or equal to 0.');
        }

        $this->container['distance'] = $distance;

        return $this;
    }

    /**
     * Gets time
     *
     * @return mixed|null
     */
    public function getTime()
    {
        return $this->container['time'];
    }

    /**
     * Sets time
     *
     * @param mixed|null $time time
     *
     * @return self
     */
    public function setTime($time)
    {
        if (is_null($time)) {
            array_push($this->openAPINullablesSetToNull, 'time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($time) && (mb_strlen($time) > 8)) {
            throw new \InvalidArgumentException('invalid length for $time when calling RecordDTO., must be smaller than or equal to 8.');
        }
        if (!is_null($time) && (mb_strlen($time) < 0)) {
            throw new \InvalidArgumentException('invalid length for $time when calling RecordDTO., must be bigger than or equal to 0.');
        }

        $this->container['time'] = $time;

        return $this;
    }

    /**
     * Gets race_type
     *
     * @return \Idealogic\RegistrationAPI\Model\RaceTypeDTO
     */
    public function getRaceType()
    {
        return $this->container['race_type'];
    }

    /**
     * Sets race_type
     *
     * @param \Idealogic\RegistrationAPI\Model\RaceTypeDTO $race_type race_type
     *
     * @return self
     */
    public function setRaceType($race_type)
    {
        if (is_null($race_type)) {
            throw new \InvalidArgumentException('non-nullable race_type cannot be null');
        }
        $this->container['race_type'] = $race_type;

        return $this;
    }

    /**
     * Gets category
     *
     * @return \Idealogic\RegistrationAPI\Model\CategoryDTO
     */
    public function getCategory()
    {
        return $this->container['category'];
    }

    /**
     * Sets category
     *
     * @param \Idealogic\RegistrationAPI\Model\CategoryDTO $category category
     *
     * @return self
     */
    public function setCategory($category)
    {
        if (is_null($category)) {
            throw new \InvalidArgumentException('non-nullable category cannot be null');
        }
        $this->container['category'] = $category;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


