<?php
/**
 * Series
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Idealogic\RegistrationAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Idealogic Event and Member Admin Service API
 *
 * Administrative services for managing events and members
 *
 * The version of the OpenAPI document: 2.4.15-SNAPSHOT
 * Contact: development@idealogic.co.za
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Idealogic\RegistrationAPI\Model;

use \ArrayAccess;
use \Idealogic\RegistrationAPI\ObjectSerializer;

/**
 * Series Class Doc Comment
 *
 * @category Class
 * @package  Idealogic\RegistrationAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Series implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Series';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'mixed',
        'name' => 'mixed',
        'csa_membership_required' => 'mixed',
        'csa_license_required' => 'mixed',
        'allow_uci_license' => 'mixed',
        'csa_strict_registration' => 'mixed',
        'csa_day_license_disallow' => 'mixed',
        'form_id' => 'mixed',
        'product_mode' => 'mixed',
        'custom_list1_required' => 'mixed',
        'custom_list2_required' => 'mixed',
        'custom_list3_required' => 'mixed',
        'custom_list1_name' => 'mixed',
        'custom_list2_name' => 'mixed',
        'custom_list3_name' => 'mixed',
        'product_day_license' => '\Idealogic\RegistrationAPI\Model\Product',
        'organisation_id' => 'mixed'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'int64',
        'name' => null,
        'csa_membership_required' => null,
        'csa_license_required' => null,
        'allow_uci_license' => null,
        'csa_strict_registration' => null,
        'csa_day_license_disallow' => null,
        'form_id' => 'int64',
        'product_mode' => null,
        'custom_list1_required' => null,
        'custom_list2_required' => null,
        'custom_list3_required' => null,
        'custom_list1_name' => null,
        'custom_list2_name' => null,
        'custom_list3_name' => null,
        'product_day_license' => null,
        'organisation_id' => 'int64'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => true,
        'name' => true,
        'csa_membership_required' => true,
        'csa_license_required' => true,
        'allow_uci_license' => true,
        'csa_strict_registration' => true,
        'csa_day_license_disallow' => true,
        'form_id' => true,
        'product_mode' => true,
        'custom_list1_required' => true,
        'custom_list2_required' => true,
        'custom_list3_required' => true,
        'custom_list1_name' => true,
        'custom_list2_name' => true,
        'custom_list3_name' => true,
        'product_day_license' => false,
        'organisation_id' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'csa_membership_required' => 'csaMembershipRequired',
        'csa_license_required' => 'csaLicenseRequired',
        'allow_uci_license' => 'allowUciLicense',
        'csa_strict_registration' => 'csaStrictRegistration',
        'csa_day_license_disallow' => 'csaDayLicenseDisallow',
        'form_id' => 'formId',
        'product_mode' => 'productMode',
        'custom_list1_required' => 'customList1Required',
        'custom_list2_required' => 'customList2Required',
        'custom_list3_required' => 'customList3Required',
        'custom_list1_name' => 'customList1Name',
        'custom_list2_name' => 'customList2Name',
        'custom_list3_name' => 'customList3Name',
        'product_day_license' => 'productDayLicense',
        'organisation_id' => 'organisationId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'csa_membership_required' => 'setCsaMembershipRequired',
        'csa_license_required' => 'setCsaLicenseRequired',
        'allow_uci_license' => 'setAllowUciLicense',
        'csa_strict_registration' => 'setCsaStrictRegistration',
        'csa_day_license_disallow' => 'setCsaDayLicenseDisallow',
        'form_id' => 'setFormId',
        'product_mode' => 'setProductMode',
        'custom_list1_required' => 'setCustomList1Required',
        'custom_list2_required' => 'setCustomList2Required',
        'custom_list3_required' => 'setCustomList3Required',
        'custom_list1_name' => 'setCustomList1Name',
        'custom_list2_name' => 'setCustomList2Name',
        'custom_list3_name' => 'setCustomList3Name',
        'product_day_license' => 'setProductDayLicense',
        'organisation_id' => 'setOrganisationId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'csa_membership_required' => 'getCsaMembershipRequired',
        'csa_license_required' => 'getCsaLicenseRequired',
        'allow_uci_license' => 'getAllowUciLicense',
        'csa_strict_registration' => 'getCsaStrictRegistration',
        'csa_day_license_disallow' => 'getCsaDayLicenseDisallow',
        'form_id' => 'getFormId',
        'product_mode' => 'getProductMode',
        'custom_list1_required' => 'getCustomList1Required',
        'custom_list2_required' => 'getCustomList2Required',
        'custom_list3_required' => 'getCustomList3Required',
        'custom_list1_name' => 'getCustomList1Name',
        'custom_list2_name' => 'getCustomList2Name',
        'custom_list3_name' => 'getCustomList3Name',
        'product_day_license' => 'getProductDayLicense',
        'organisation_id' => 'getOrganisationId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const PRODUCT_MODE_CATEGORY_ELSE_EVENT = 'CATEGORY_ELSE_EVENT';
    public const PRODUCT_MODE_BOTH = 'BOTH';
    public const PRODUCT_MODE_EVENT_ONLY = 'EVENT_ONLY';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getProductModeAllowableValues()
    {
        return [
            self::PRODUCT_MODE_CATEGORY_ELSE_EVENT,
            self::PRODUCT_MODE_BOTH,
            self::PRODUCT_MODE_EVENT_ONLY,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('csa_membership_required', $data ?? [], null);
        $this->setIfExists('csa_license_required', $data ?? [], null);
        $this->setIfExists('allow_uci_license', $data ?? [], null);
        $this->setIfExists('csa_strict_registration', $data ?? [], null);
        $this->setIfExists('csa_day_license_disallow', $data ?? [], null);
        $this->setIfExists('form_id', $data ?? [], null);
        $this->setIfExists('product_mode', $data ?? [], null);
        $this->setIfExists('custom_list1_required', $data ?? [], null);
        $this->setIfExists('custom_list2_required', $data ?? [], null);
        $this->setIfExists('custom_list3_required', $data ?? [], null);
        $this->setIfExists('custom_list1_name', $data ?? [], null);
        $this->setIfExists('custom_list2_name', $data ?? [], null);
        $this->setIfExists('custom_list3_name', $data ?? [], null);
        $this->setIfExists('product_day_license', $data ?? [], null);
        $this->setIfExists('organisation_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 100)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 100.";
        }

        if ((mb_strlen($this->container['name']) < 0)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 0.";
        }

        if ($this->container['csa_membership_required'] === null) {
            $invalidProperties[] = "'csa_membership_required' can't be null";
        }
        if ($this->container['csa_license_required'] === null) {
            $invalidProperties[] = "'csa_license_required' can't be null";
        }
        if ($this->container['allow_uci_license'] === null) {
            $invalidProperties[] = "'allow_uci_license' can't be null";
        }
        if ($this->container['csa_strict_registration'] === null) {
            $invalidProperties[] = "'csa_strict_registration' can't be null";
        }
        if ($this->container['csa_day_license_disallow'] === null) {
            $invalidProperties[] = "'csa_day_license_disallow' can't be null";
        }
        $allowedValues = $this->getProductModeAllowableValues();
        if (!is_null($this->container['product_mode']) && !in_array($this->container['product_mode'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'product_mode', must be one of '%s'",
                $this->container['product_mode'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['custom_list1_required'] === null) {
            $invalidProperties[] = "'custom_list1_required' can't be null";
        }
        if ($this->container['custom_list2_required'] === null) {
            $invalidProperties[] = "'custom_list2_required' can't be null";
        }
        if ($this->container['custom_list3_required'] === null) {
            $invalidProperties[] = "'custom_list3_required' can't be null";
        }
        if (!is_null($this->container['custom_list1_name']) && (mb_strlen($this->container['custom_list1_name']) > 50)) {
            $invalidProperties[] = "invalid value for 'custom_list1_name', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['custom_list1_name']) && (mb_strlen($this->container['custom_list1_name']) < 0)) {
            $invalidProperties[] = "invalid value for 'custom_list1_name', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['custom_list2_name']) && (mb_strlen($this->container['custom_list2_name']) > 50)) {
            $invalidProperties[] = "invalid value for 'custom_list2_name', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['custom_list2_name']) && (mb_strlen($this->container['custom_list2_name']) < 0)) {
            $invalidProperties[] = "invalid value for 'custom_list2_name', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['custom_list3_name']) && (mb_strlen($this->container['custom_list3_name']) > 50)) {
            $invalidProperties[] = "invalid value for 'custom_list3_name', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['custom_list3_name']) && (mb_strlen($this->container['custom_list3_name']) < 0)) {
            $invalidProperties[] = "invalid value for 'custom_list3_name', the character length must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return mixed|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param mixed|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            array_push($this->openAPINullablesSetToNull, 'id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return mixed
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param mixed $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            array_push($this->openAPINullablesSetToNull, 'name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($name) && (mb_strlen($name) > 100)) {
            throw new \InvalidArgumentException('invalid length for $name when calling Series., must be smaller than or equal to 100.');
        }
        if (!is_null($name) && (mb_strlen($name) < 0)) {
            throw new \InvalidArgumentException('invalid length for $name when calling Series., must be bigger than or equal to 0.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets csa_membership_required
     *
     * @return mixed
     */
    public function getCsaMembershipRequired()
    {
        return $this->container['csa_membership_required'];
    }

    /**
     * Sets csa_membership_required
     *
     * @param mixed $csa_membership_required csa_membership_required
     *
     * @return self
     */
    public function setCsaMembershipRequired($csa_membership_required)
    {
        if (is_null($csa_membership_required)) {
            array_push($this->openAPINullablesSetToNull, 'csa_membership_required');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('csa_membership_required', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['csa_membership_required'] = $csa_membership_required;

        return $this;
    }

    /**
     * Gets csa_license_required
     *
     * @return mixed
     */
    public function getCsaLicenseRequired()
    {
        return $this->container['csa_license_required'];
    }

    /**
     * Sets csa_license_required
     *
     * @param mixed $csa_license_required csa_license_required
     *
     * @return self
     */
    public function setCsaLicenseRequired($csa_license_required)
    {
        if (is_null($csa_license_required)) {
            array_push($this->openAPINullablesSetToNull, 'csa_license_required');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('csa_license_required', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['csa_license_required'] = $csa_license_required;

        return $this;
    }

    /**
     * Gets allow_uci_license
     *
     * @return mixed
     */
    public function getAllowUciLicense()
    {
        return $this->container['allow_uci_license'];
    }

    /**
     * Sets allow_uci_license
     *
     * @param mixed $allow_uci_license allow_uci_license
     *
     * @return self
     */
    public function setAllowUciLicense($allow_uci_license)
    {
        if (is_null($allow_uci_license)) {
            array_push($this->openAPINullablesSetToNull, 'allow_uci_license');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('allow_uci_license', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['allow_uci_license'] = $allow_uci_license;

        return $this;
    }

    /**
     * Gets csa_strict_registration
     *
     * @return mixed
     */
    public function getCsaStrictRegistration()
    {
        return $this->container['csa_strict_registration'];
    }

    /**
     * Sets csa_strict_registration
     *
     * @param mixed $csa_strict_registration csa_strict_registration
     *
     * @return self
     */
    public function setCsaStrictRegistration($csa_strict_registration)
    {
        if (is_null($csa_strict_registration)) {
            array_push($this->openAPINullablesSetToNull, 'csa_strict_registration');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('csa_strict_registration', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['csa_strict_registration'] = $csa_strict_registration;

        return $this;
    }

    /**
     * Gets csa_day_license_disallow
     *
     * @return mixed
     */
    public function getCsaDayLicenseDisallow()
    {
        return $this->container['csa_day_license_disallow'];
    }

    /**
     * Sets csa_day_license_disallow
     *
     * @param mixed $csa_day_license_disallow csa_day_license_disallow
     *
     * @return self
     */
    public function setCsaDayLicenseDisallow($csa_day_license_disallow)
    {
        if (is_null($csa_day_license_disallow)) {
            array_push($this->openAPINullablesSetToNull, 'csa_day_license_disallow');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('csa_day_license_disallow', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['csa_day_license_disallow'] = $csa_day_license_disallow;

        return $this;
    }

    /**
     * Gets form_id
     *
     * @return mixed|null
     */
    public function getFormId()
    {
        return $this->container['form_id'];
    }

    /**
     * Sets form_id
     *
     * @param mixed|null $form_id form_id
     *
     * @return self
     */
    public function setFormId($form_id)
    {
        if (is_null($form_id)) {
            array_push($this->openAPINullablesSetToNull, 'form_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('form_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['form_id'] = $form_id;

        return $this;
    }

    /**
     * Gets product_mode
     *
     * @return mixed|null
     */
    public function getProductMode()
    {
        return $this->container['product_mode'];
    }

    /**
     * Sets product_mode
     *
     * @param mixed|null $product_mode product_mode
     *
     * @return self
     */
    public function setProductMode($product_mode)
    {
        if (is_null($product_mode)) {
            array_push($this->openAPINullablesSetToNull, 'product_mode');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('product_mode', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getProductModeAllowableValues();
        if (!is_null($product_mode) && !in_array($product_mode, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'product_mode', must be one of '%s'",
                    $product_mode,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['product_mode'] = $product_mode;

        return $this;
    }

    /**
     * Gets custom_list1_required
     *
     * @return mixed
     */
    public function getCustomList1Required()
    {
        return $this->container['custom_list1_required'];
    }

    /**
     * Sets custom_list1_required
     *
     * @param mixed $custom_list1_required custom_list1_required
     *
     * @return self
     */
    public function setCustomList1Required($custom_list1_required)
    {
        if (is_null($custom_list1_required)) {
            array_push($this->openAPINullablesSetToNull, 'custom_list1_required');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('custom_list1_required', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['custom_list1_required'] = $custom_list1_required;

        return $this;
    }

    /**
     * Gets custom_list2_required
     *
     * @return mixed
     */
    public function getCustomList2Required()
    {
        return $this->container['custom_list2_required'];
    }

    /**
     * Sets custom_list2_required
     *
     * @param mixed $custom_list2_required custom_list2_required
     *
     * @return self
     */
    public function setCustomList2Required($custom_list2_required)
    {
        if (is_null($custom_list2_required)) {
            array_push($this->openAPINullablesSetToNull, 'custom_list2_required');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('custom_list2_required', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['custom_list2_required'] = $custom_list2_required;

        return $this;
    }

    /**
     * Gets custom_list3_required
     *
     * @return mixed
     */
    public function getCustomList3Required()
    {
        return $this->container['custom_list3_required'];
    }

    /**
     * Sets custom_list3_required
     *
     * @param mixed $custom_list3_required custom_list3_required
     *
     * @return self
     */
    public function setCustomList3Required($custom_list3_required)
    {
        if (is_null($custom_list3_required)) {
            array_push($this->openAPINullablesSetToNull, 'custom_list3_required');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('custom_list3_required', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['custom_list3_required'] = $custom_list3_required;

        return $this;
    }

    /**
     * Gets custom_list1_name
     *
     * @return mixed|null
     */
    public function getCustomList1Name()
    {
        return $this->container['custom_list1_name'];
    }

    /**
     * Sets custom_list1_name
     *
     * @param mixed|null $custom_list1_name custom_list1_name
     *
     * @return self
     */
    public function setCustomList1Name($custom_list1_name)
    {
        if (is_null($custom_list1_name)) {
            array_push($this->openAPINullablesSetToNull, 'custom_list1_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('custom_list1_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($custom_list1_name) && (mb_strlen($custom_list1_name) > 50)) {
            throw new \InvalidArgumentException('invalid length for $custom_list1_name when calling Series., must be smaller than or equal to 50.');
        }
        if (!is_null($custom_list1_name) && (mb_strlen($custom_list1_name) < 0)) {
            throw new \InvalidArgumentException('invalid length for $custom_list1_name when calling Series., must be bigger than or equal to 0.');
        }

        $this->container['custom_list1_name'] = $custom_list1_name;

        return $this;
    }

    /**
     * Gets custom_list2_name
     *
     * @return mixed|null
     */
    public function getCustomList2Name()
    {
        return $this->container['custom_list2_name'];
    }

    /**
     * Sets custom_list2_name
     *
     * @param mixed|null $custom_list2_name custom_list2_name
     *
     * @return self
     */
    public function setCustomList2Name($custom_list2_name)
    {
        if (is_null($custom_list2_name)) {
            array_push($this->openAPINullablesSetToNull, 'custom_list2_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('custom_list2_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($custom_list2_name) && (mb_strlen($custom_list2_name) > 50)) {
            throw new \InvalidArgumentException('invalid length for $custom_list2_name when calling Series., must be smaller than or equal to 50.');
        }
        if (!is_null($custom_list2_name) && (mb_strlen($custom_list2_name) < 0)) {
            throw new \InvalidArgumentException('invalid length for $custom_list2_name when calling Series., must be bigger than or equal to 0.');
        }

        $this->container['custom_list2_name'] = $custom_list2_name;

        return $this;
    }

    /**
     * Gets custom_list3_name
     *
     * @return mixed|null
     */
    public function getCustomList3Name()
    {
        return $this->container['custom_list3_name'];
    }

    /**
     * Sets custom_list3_name
     *
     * @param mixed|null $custom_list3_name custom_list3_name
     *
     * @return self
     */
    public function setCustomList3Name($custom_list3_name)
    {
        if (is_null($custom_list3_name)) {
            array_push($this->openAPINullablesSetToNull, 'custom_list3_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('custom_list3_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($custom_list3_name) && (mb_strlen($custom_list3_name) > 50)) {
            throw new \InvalidArgumentException('invalid length for $custom_list3_name when calling Series., must be smaller than or equal to 50.');
        }
        if (!is_null($custom_list3_name) && (mb_strlen($custom_list3_name) < 0)) {
            throw new \InvalidArgumentException('invalid length for $custom_list3_name when calling Series., must be bigger than or equal to 0.');
        }

        $this->container['custom_list3_name'] = $custom_list3_name;

        return $this;
    }

    /**
     * Gets product_day_license
     *
     * @return \Idealogic\RegistrationAPI\Model\Product|null
     */
    public function getProductDayLicense()
    {
        return $this->container['product_day_license'];
    }

    /**
     * Sets product_day_license
     *
     * @param \Idealogic\RegistrationAPI\Model\Product|null $product_day_license product_day_license
     *
     * @return self
     */
    public function setProductDayLicense($product_day_license)
    {
        if (is_null($product_day_license)) {
            throw new \InvalidArgumentException('non-nullable product_day_license cannot be null');
        }
        $this->container['product_day_license'] = $product_day_license;

        return $this;
    }

    /**
     * Gets organisation_id
     *
     * @return mixed|null
     */
    public function getOrganisationId()
    {
        return $this->container['organisation_id'];
    }

    /**
     * Sets organisation_id
     *
     * @param mixed|null $organisation_id organisation_id
     *
     * @return self
     */
    public function setOrganisationId($organisation_id)
    {
        if (is_null($organisation_id)) {
            array_push($this->openAPINullablesSetToNull, 'organisation_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('organisation_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['organisation_id'] = $organisation_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


